export const rawTestResultData = {
  hardSkill: [
    { name: "Account Management", pass: 20271, fail: 7095 },
    { name: "Business Advisory", pass: 13305, fail: 0 },
    { name: "Business Environment Analysis", pass: 0, fail: 12434 },
    { name: "Business Opportunity Development", pass: 15809, fail: 0 },
    { name: "Credit Assessment", pass: 18544, fail: 8822 },
    { name: "Customer Acquisition Management", pass: 10533, fail: 0 },
    { name: "Customer Relationship Management", pass: 17652, fail: 9714 },
    { name: "Financial Literacy Desimination", pass: 15429, fail: 0 },
    { name: "Product Advisory", pass: 20016, fail: 7350 },
  ],
  regionalData: [
    { name: "Regional Office Manado", value: 21.92 },
    { name: "Regional Office Medan", value: 25.92 },
    { name: "Regional Office Jayapura", value: 31.32 },
    { name: "Regional Office Makassar", value: 34.65 },
    { name: "Regional Office Jakarta 2", value: 35.47 },
    { name: "Regional Office Padang", value: 36.28 },
    { name: "Regional Office Palembang", value: 37.13 },
    { name: "Regional Office Banjarmasin", value: 37.23 },
    { name: "Regional Office Surabaya", value: 38.17 },
    { name: "Regional Office Pekanbaru", value: 38.3 },
    { name: "Regional Office Bandung", value: 39.95 },
    { name: "Regional Office Jakarta 3", value: 39.86 },
    { name: "Regional Office Semarang", value: 41.45 },
    { name: "Regional Office Jakarta 1", value: 42.58 },
    { name: "Regional Office Denpasar", value: 47.1 },
    { name: "Regional Office Malang", value: 49.58 },
    { name: "Regional Office Yogyakarta", value: 51.23 },
  ],
  rank: [
    { unit: "Regional Office Bandar Lampung - UNIT PADANG JATI", pass: 100 },
    { unit: "Regional Office Bandar Lampung - UNIT PANJANG", pass: 100 },
    { unit: "Regional Office Bandar Lampung - UNIT PONDOK KELAPA", pass: 100 },
    { unit: "Regional Office Bandar Lampung - UNIT PULAU BAAI", pass: 100 },
    { unit: "Regional Office Bandar Lampung - UNIT PUNGGUR", pass: 100 },
    { unit: "Regional Office Bandar Lampung - UNIT SRI BAWONO", pass: 100 },
    { unit: "Regional Office Bandung - BRI UNIT BANTARUJUG", pass: 100 },
    { unit: "Regional Office Bandung - BRI UNIT CIHAPIT", pass: 100 },
    { unit: "Regional Office Bandung - BRI UNIT CINYASAG", pass: 100 },
    { unit: "Regional Office Bandung - BRI UNIT GUNUNGSARI", pass: 100 },
    { unit: "Another Unit", pass: 99 },
  ],
};
